### ISSUE TITLE
task: Setup code coverage

### ISSUE THREAD

**Issue by dgarros** [opsmill/infrahub-sdk-python#50]
### Component

CI/CD

### Task Description

During the migration, the integration with a code coverage tool has been temporarily removed, we need to reactivate.

In `infrahub` we are using https://coveralls.io but I think it would be good to try something else to see they they compare.
I've seen multiple projects implementing https://about.codecov.io/ successfully.

**Comment by ogenstad** [comment]
Closing as done.
