### ISSUE TITLE
bug: infrahubctl transform does not setup the InfrahubTransform class with a InfrahubClient instance

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub-sdk-python#8]
### Component

Python SDK

### Infrahub version

0.12.4

### Current Behavior

When you run a Python transformation using the `infrahubctl transform` command, it does not set up the client property of the InfrahubTransform class. This is different from how the same transform would be run in Infrahub, in that case the client property would be properly set.

This makes developing transformations hard, as the behavior is different depending on the way the transformation is run. 

### Expected Behavior

The client property of the InfrahubTransform class is properly set with an initialized InfrahubClient object.

### Steps to Reproduce

- load infrahub with demo schema and data
- fork infrahub-demo-edge
- set up the forked repository as an external repository in Infrahub
- create a local clone of the forked repository
- modify the `transforms/openconfig.py` script
- add `print(self.client.mode)` statement on line 8
- save the file
- run the transformation locally using `infrahubctl transform OCInterfaces device=atl1-edge1`
- commit change and push to remote
- run the transformation in Infrahub `http://localhost:8000/api/transform/python/OCinterfaces?device=atl1-edge1`

### Additional Information

There seems to be a difference in how we instantiate the transform class:
https://github.com/opsmill/infrahub/blob/develop/backend/infrahub/git/integrator.py#L1195
https://github.com/opsmill/infrahub/blob/develop/python_sdk/infrahub_sdk/transforms.py#L111

**Comment by ogenstad** [comment]
Fixed in #7.
